ARG IMAGE=python:3.10.12
FROM $IMAGE as base
RUN mkdir /app
WORKDIR /app
COPY requirements.txt /tmp
RUN pip install --upgrade pip && pip install -r /tmp/requirements.txt && rm /tmp/requirements.txt

FROM base 
COPY app /app
COPY model /app/model

EXPOSE 8000

CMD ["/usr/local/bin/gunicorn","-b","0.0.0.0:8000","-w","1","app:app"]





